Traceback (most recent call last):
  File "C:\Users\tomui\Desktop\meteo\meteolt_app\meteolt_app.py", line 409, in <module>
    app = App()
          ^^^^^
  File "C:\Users\tomui\Desktop\meteo\meteolt_app\meteolt_app.py", line 72, in __init__
    self.table = Table(self.tab2, self.terminal)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomui\Desktop\meteo\meteolt_app\calculations.py", line 22, in __init__
    self.insert_data()
  File "C:\Users\tomui\Desktop\meteo\meteolt_app\calculations.py", line 52, in insert_data
    self.data = Calculations().get_statistics()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomui\Desktop\meteo\meteolt_app\calculations.py", line 93, in get_statistics
    with open(f'data/csv_combined_vln_{day}.csv', 'r') as vln_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/csv_combined_vln_Day 1.csv'
